id = "java_lsp"
name = "Java (LSP)"
description = "Java support."
version = "0.1.0"
schema_version = 1
authors = [
    "Sascha Häusler <saeschdivara@gmail.com>"
]
repository = "https://github.com/zed-industries/zed"

[language_servers.hls]
name = "Haskell Language Server"
language = "Haskell"

[grammars.haskell]
repository = "https://github.com/tree-sitter/tree-sitter-haskell"
commit = "8a99848fc734f9c4ea523b3f2a07df133cbbcec2"