id = "java_lsp"
name = "Java (LSP)"
description = "Java support."
version = "0.1.0"
schema_version = 1
authors = [
    "Sascha Häusler <saeschdivara@gmail.com>"
]
repository = "https://github.com/zed-industries/zed"

[language_servers.jlsp]
name = "Java Language Server"
language = "Java"

[grammars.java]
repository = "https://github.com/tree-sitter/tree-sitter-java"
commit = "99b29f1ed957b3b424b6e21f57bd21a9732a622a"