id = "java_lsp"
name = "Java (LSP)"
description = "Java support."
version = "0.1.0"
schema_version = 1
authors = [
    "Sascha Häusler <saeschdivara@gmail.com>"
]
repository = "https://github.com/zed-industries/zed"

[language_servers.jlsp]
name = "Java Language Server"
language = "Java"

[grammars.haskell]
repository = "https://github.com/saeschdivara/zed-java-lsp"
commit = "33d34c080f260a47de3c2d4ad173547b5c65077e"